"""
DPO (Direct Preference Optimization) Fine-tuning for SPARQL generation models.

This script trains a language model using DPO to prefer correct SPARQL queries
over incorrect ones generated by few-shot prompting.

Requirements:
- transformers >= 4.36.0
- trl >= 0.7.0
- peft >= 0.7.0
- torch >= 2.0.0
- datasets
- wandb (optional)
"""

import json
import argparse
import logging
from pathlib import Path
from typing import Dict, Optional
import random

import torch
from torch.utils.data import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
    Trainer,
)
from trl import DPOTrainer
from peft import LoraConfig, get_peft_model
from datasets import load_dataset

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class DPODataset(Dataset):
    """Custom Dataset for DPO training."""
    
    def __init__(
        self,
        data_path: Path,
        tokenizer,
        max_length: int = 1024,
        prompt_template: str = None
    ):
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.prompt_template = prompt_template or "{prompt}"
        self.data = self._load_data(data_path)
    
    def _load_data(self, path: Path):
        """Load JSONL dataset."""
        data = []
        with open(path, 'r') as f:
            for line in f:
                if line.strip():
                    data.append(json.loads(line))
        logger.info(f"Loaded {len(data)} examples from {path}")
        return data
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        example = self.data[idx]
        
        # Format prompt
        prompt = self.prompt_template.format(prompt=example['prompt'])
        
        # Tokenize
        tokens = self.tokenizer(
            prompt,
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        # Add chosen and rejected completions
        chosen_tokens = self.tokenizer(
            example['chosen'],
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        rejected_tokens = self.tokenizer(
            example['rejected'],
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        return {
            'prompt': prompt,
            'chosen': example['chosen'],
            'rejected': example['rejected'],
            'prompt_input_ids': tokens['input_ids'].squeeze(),
            'prompt_attention_mask': tokens['attention_mask'].squeeze(),
            'chosen_input_ids': chosen_tokens['input_ids'].squeeze(),
            'chosen_attention_mask': chosen_tokens['attention_mask'].squeeze(),
            'rejected_input_ids': rejected_tokens['input_ids'].squeeze(),
            'rejected_attention_mask': rejected_tokens['attention_mask'].squeeze(),
        }


def load_config(config_path: Path) -> Dict:
    """Load training configuration."""
    import yaml
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)


def setup_model_and_tokenizer(
    model_name: str,
    use_4bit: bool = True,
    use_8bit: bool = False,
    lora_config: Optional[Dict] = None
):
    """Setup model and tokenizer with quantization and LoRA."""
    
    logger.info(f"Loading model: {model_name}")
    
    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    # Quantization config
    if use_4bit:
        logger.info("Using 4-bit quantization")
        quantization_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
        )
    elif use_8bit:
        logger.info("Using 8-bit quantization")
        quantization_config = BitsAndBytesConfig(load_in_8bit=True)
    else:
        quantization_config = None
    
    # Load model
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=quantization_config,
        device_map="auto",
        torch_dtype=torch.bfloat16 if use_4bit else torch.float32,
        trust_remote_code=True,
    )
    
    # Setup LoRA if provided
    if lora_config:
        logger.info("Applying LoRA configuration")
        lora = LoraConfig(
            r=lora_config.get('r', 8),
            lora_alpha=lora_config.get('lora_alpha', 16),
            target_modules=lora_config.get('target_modules', ['q_proj', 'v_proj']),
            lora_dropout=lora_config.get('lora_dropout', 0.05),
            bias=lora_config.get('bias', 'none'),
            task_type=lora_config.get('task_type', 'CAUSAL_LM'),
        )
        model = get_peft_model(model, lora)
        model.print_trainable_parameters()
    
    return model, tokenizer


def setup_training_args(config: Dict, output_dir: Path) -> TrainingArguments:
    """Setup training arguments."""
    training_config = config.get('training', {})
    
    return TrainingArguments(
        output_dir=str(output_dir),
        num_train_epochs=training_config.get('num_epochs', 3),
        per_device_train_batch_size=training_config.get('batch_size', 4),
        per_device_eval_batch_size=training_config.get('eval_batch_size', 8),
        learning_rate=training_config.get('learning_rate', 5e-5),
        weight_decay=training_config.get('weight_decay', 0.01),
        warmup_steps=training_config.get('warmup_steps', 100),
        gradient_accumulation_steps=training_config.get('gradient_accumulation_steps', 2),
        max_grad_norm=training_config.get('max_grad_norm', 1.0),
        save_strategy=training_config.get('save_strategy', 'epoch'),
        evaluation_strategy=training_config.get('eval_strategy', 'epoch'),
        logging_steps=training_config.get('logging_steps', 10),
        seed=training_config.get('seed', 42),
        fp16=False,
        bf16=True,
        gradient_checkpointing=True,
        optim="paged_adamw_8bit",
        report_to=["wandb"] if config.get('logging', {}).get('use_wandb', False) else [],
    )


def load_dpo_dataset(
    train_path: Path,
    eval_path: Path,
    tokenizer,
    max_length: int = 1024,
):
    """Load datasets for DPO training."""
    logger.info(f"Loading training dataset from {train_path}")
    train_dataset = DPODataset(
        train_path,
        tokenizer,
        max_length=max_length
    )
    
    logger.info(f"Loading evaluation dataset from {eval_path}")
    eval_dataset = DPODataset(
        eval_path,
        tokenizer,
        max_length=max_length
    )
    
    return train_dataset, eval_dataset


def train_dpo_model(
    config_path: Path,
    output_dir: Path,
    resume_from_checkpoint: Optional[Path] = None,
):
    """Main training function."""
    
    # Load config
    config = load_config(config_path)
    logger.info(f"Loaded configuration from {config_path}")
    
    # Create output directory
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Save config to output
    with open(output_dir / "dpo_config.json", 'w') as f:
        json.dump(config, f, indent=2)
    
    # Setup model and tokenizer
    model_config = config.get('model', {})
    model, tokenizer = setup_model_and_tokenizer(
        model_name=model_config.get('name', 'google/gemini-2.0-flash'),
        use_4bit=model_config.get('load_in_4bit', True),
        use_8bit=model_config.get('load_in_8bit', False),
        lora_config=model_config.get('lora', None),
    )
    
    # Load datasets
    dataset_config = config.get('dataset', {})
    train_path = Path(dataset_config.get('train_path'))
    eval_path = Path(dataset_config.get('eval_path'))
    
    train_dataset, eval_dataset = load_dpo_dataset(
        train_path,
        eval_path,
        tokenizer,
        max_length=dataset_config.get('max_length', 1024),
    )
    
    # Setup training arguments
    training_args = setup_training_args(config, output_dir)
    
    # Setup DPO trainer
    dpo_config = config.get('dpo', {})
    
    logger.info("Setting up DPO trainer...")
    trainer = DPOTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        beta=dpo_config.get('beta', 0.1),
        loss_type=dpo_config.get('loss_type', 'sigmoid'),
        label_smoothing=dpo_config.get('label_smoothing', 0.0),
        sanity_check=dpo_config.get('sanity_check', False),
    )
    
    # Train
    logger.info("Starting DPO training...")
    train_result = trainer.train(
        resume_from_checkpoint=resume_from_checkpoint
    )
    
    # Save results
    logger.info(f"Training completed!")
    logger.info(f"Training metrics: {train_result.metrics}")
    
    # Save model
    logger.info(f"Saving model to {output_dir}")
    trainer.save_model(output_dir / "final_model")
    tokenizer.save_pretrained(output_dir / "final_model")
    
    # Save training results
    with open(output_dir / "training_results.json", 'w') as f:
        json.dump(train_result.metrics, f, indent=2)
    
    logger.info("Training pipeline completed successfully!")
    
    return trainer, train_result


def main():
    parser = argparse.ArgumentParser(description="DPO Fine-tuning for SPARQL generation")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path(__file__).parent.parent / "configs" / "dpo_config.yaml",
        help="Path to training configuration file"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent.parent / "models" / "dpo_finetuned",
        help="Output directory for trained model"
    )
    parser.add_argument(
        "--resume-from-checkpoint",
        type=Path,
        default=None,
        help="Resume training from checkpoint"
    )
    parser.add_argument(
        "--log-level",
        type=str,
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging level"
    )
    
    args = parser.parse_args()
    
    # Set logging level
    logging.getLogger().setLevel(getattr(logging, args.log_level))
    
    # Run training
    try:
        trainer, results = train_dpo_model(
            args.config,
            args.output_dir,
            args.resume_from_checkpoint
        )
        return 0
    except Exception as e:
        logger.error(f"Training failed: {e}", exc_info=True)
        return 1


if __name__ == "__main__":
    exit(main())
